<a href="https://colab.research.google.com/github/HuynhQuocDan/Artificial-Intelligence/blob/main/week8_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn import datasets
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split #hàm này dùng để cắt dữ liệu gốc thành 2 phần, một phần để train còn một phần để test
from sklearn.metrics import accuracy_score #đo độ chính xác
from sklearn.preprocessing import StandardScaler #vì dữ liệu không đều nhau, chênh lệch quá lớn, hàm này để scale, chuẩn hóa dữ liệu trong tập dữ liệu gốc, nếu không xử lý thì sai số sau train sẽ sai số lớn
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [19]:
#Bai 4 xac dinh loai cua
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

data = pd.read_csv('crabs.csv')
data.head()

#xóa đi các cột không liên quan
X = data[data['speies']=='B'] # loc lay loai B
X = X.drop(['speies','index'],axis= 1)
X.sex = X.sex.apply(lambda x: x.replace("M","0"))
X.sex = X.sex.apply(lambda x: x.replace("F","1"))
X.head(100)

   sex  fontallip  rearwidth  length  width  depth
0    0        8.1        6.7    16.1   19.0    7.0
1    0        8.8        7.7    18.1   20.8    7.4
2    0        9.2        7.8    19.0   22.4    7.7
3    0        9.6        7.9    20.1   23.1    8.2
4    0        9.8        8.0    20.3   23.0    8.2
..  ..        ...        ...     ...    ...    ...
95   1       16.4       14.0    34.2   39.8   15.2
96   1       16.7       16.1    36.6   41.9   15.4
97   1       17.4       16.9    38.2   44.1   16.6
98   1       17.5       16.7    38.6   44.5   17.0
99   1       19.2       16.5    40.9   47.9   18.1

[100 rows x 6 columns]

In [ ]:
sc = StandardScaler()

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.3)
sc.fit(X_train)

X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)

model = Perceptron(max_iter=10000, eta0 = 0.1, random_state=0) #dat so lan hoc va toc do hoc
model.fit(X_train_std, y_train)
y_pred = model.predict(X_test_std)
print(y_pred)
print(y_test)